package edu.eci.cosw.jpa.sample.model;
// Generated Mar 9, 2016 7:01:57 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;


/**
 * Cursos generated by hbm2java
 */

@Entity
@Table(name = "CURSOS")
public class Curso  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String nemonico;
     private Set<Estudiante> estudiantes = new HashSet<>(0);

    public Curso() {
    }

	
    public Curso(int id, String nombre, String nemonico) {
        this.setId(id);
        this.setNombre(nombre);
        this.setNemonico(nemonico);
    }
    
    public Curso(int id, String nombre, String nemonico, Set<Estudiante> estudiantes) {
       this.setId(id);
       this.setNombre(nombre);
       this.setNemonico(nemonico);
       this.setEstudiantes(estudiantes);
    }
   
    @Id
    @Column (name = "id")
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column (name = "nombre")
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column (name = "nemonico")
    public String getNemonico() {
        return this.nemonico;
    }
    
    public void setNemonico(String nemonico) {
        this.nemonico = nemonico;
    }
    
    @ManyToMany(mappedBy = "cursos",fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    public Set<Estudiante> getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set<Estudiante> estudiantes) {
        this.estudiantes = estudiantes;
    }

    @Override
    public String toString() {
        return "Curso{" + "id=" + id + ", nombre=" + nombre + ", nemonico=" + nemonico + '}';
    }

    
    
}